### ISSUE TITLE
full windowed streetview, possible?

### ISSUE THREAD

**Issue by jolokia74** [barryhunter/classygmaps#35] opened 2015-06-11 20:50 UTC
when in overhead view and I enter streetview, the view divides in half horizontally. is it possible to maximize the street? possibly pop that up in a new window? the split view is just too small. thanks!

**Comment by barryhunter** [comment] 2015-06-12 16:24
Duplicate of https://github.com/barryhunter/classygmaps/issues/1

**Closed by barryhunter** 2015-06-12 16:24 UTC
