### ISSUE TITLE
Search Nearby

### ISSUE THREAD

**Issue by CRR1335** [barryhunter/classygmaps#44] opened 2015-06-26 13:01 UTC
I'm not sure if it has already been mentioned or if it's even possible, but Classic Google Maps had a "search nearby" option.  You'd type in a primary address in the search field, and for example, search nearby for "dentists".  There would be a column on the left that had a list of results for all the nearby dentists, with business name, address, telephone number, website, and distance (mileage) from primary address.  There were multiple pages of results, with each page showing a list of 10 businesses.

The new google maps still has the "search nearby" option, but it only has a list of 10 results, with no additional pages, and it doesn't list the telephone number or the distance from the primary address.

I'm not sure if you are able to implement this into Classy Maps, but I thought I would ask?  Other map sites I've tried have a few of these features, but not one has all of them combined.

Thank you for your time.

**Comment by barryhunter** [comment] 2015-07-07 20:06
Actully, this possibly a duplicate of https://github.com/barryhunter/classygmaps/issues/16

**Closed by barryhunter** 2015-07-07 20:06 UTC
Labels: enhancement
