### ISSUE TITLE
Full-screen street view

### ISSUE THREAD

**Issue by borderthinking** [barryhunter/classygmaps#38] opened 2015-06-13 14:40 UTC
I see others have suggested this and entries are marked Closed. Does this mean it is not possible? It's what I am looking for, with the easy non-jerky movement that old google street view had. Not split-screen.

**Comment by lol666** [comment] 2015-06-14 14:35
They're probably like Google and just don't care.

**Comment by barryhunter** [comment] 2015-06-14 14:49
@borderthinking, the requests of full-screen that I've seen have just asking for a way to make sv full-screen. Which is a what issue #1 is about, change the display option. I originally build this because I specifially wanted split screen view. But do realise there is times when other views could be useful. 

Not seen 'non-jerky' mentioned before. But I think we are pretty limited what we get here. ClassyGMaps is built with the Google Maps API. And the SV viewer is implemented in Javascript. Whereas the real classic used Flash. I dont think there is anyway for the API to invoke a flash viewer.  

@lol666 
Who are 'they' that you refer to? You do realise ClassyGMaps is being built by one person (me!) in my free time. There is a limit to how much time I can devote to it. As much as would like to can't spend days implementing stuff.

**Comment by borderthinking** [comment] 2015-06-14 20:19
thank you, barry. i realise there's an ambiguity, i don't mean 'full screen' as in pulling the view out to the machine's corners but having street view on the whole map as opposed to in split-screen.

as for jerky movement, i am a geographer who used classic google street view daily for years, it was smooth in movement, flexible, able to tilt up and down as well as side to side and movable with the cursorr. the new google map lite version of street view is jerky and bumpy in movements  while the non-lite movement zooms very fast - actually making me dizzy so  can't use it.

i don't understand apis or how you've done what you've done or why the classic street view should act so different from the new one. i am mystified. but again, thank you.

**Comment by mark0122** [comment] 2015-07-04 11:56
Hello. First of all, I would like to thank you for your time and effort to make some sort of classic maps. And also I would like to apologize for my poor English.
I attached a photo here with my suggestions. This way I save some time and some words for you to read. :)
Could you please let me know if any of those can be made?
Thanks in advance!
![maptest](https://cloud.githubusercontent.com/assets/13176230/8507823/a59d1f92-2243-11e5-8c3a-e671e828f7b2.jpg)

**Comment by barryhunter** [comment] 2015-07-07 20:10
I'm closing this as a duplicate of https://github.com/barryhunter/classygmaps/issues/1, 

the actual options to change display of SV has been started see the linked issue. 

Alas the other note about 'smoothness' - as a API user not sure anything can be done. We dont have access to the Flash viewer that Google used in Classic Maps.

**Closed by barryhunter** 2015-07-07 20:10 UTC
