### ISSUE TITLE
undo split screen?

### ISSUE THREAD

**Issue by sandpiper1** [barryhunter/classygmaps#34] opened 2015-06-11 10:30 UTC
I can see where the split screen might come in handy while in street view, but I find it takes up too much space and could not find a way of undoing the split.

Ps Thank you SO much for recreating the Classic, but I have a feeling it is going to be even better!

**Comment by barryhunter** [comment] 2015-06-11 10:33
Duplicate of https://github.com/barryhunter/classygmaps/issues/1

**Closed by barryhunter** 2015-06-11 10:33 UTC
Labels: duplicate

**Comment by sandpiper1** [comment] 2015-06-11 13:18
Oh....sorry!
