### ISSUE TITLE
Direction on street view

### ISSUE THREAD

**Issue by GrahamStelmach** [barryhunter/classygmaps#76] opened 2015-08-16 16:55 UTC
Brilliant prototype so far and I really wish you all the best in developing this further.
One enhancement suggestion is perhaps to overlay the blue "direction" line from the map view onto the street view. This would mean that in a "full screen" street view it would still be clear what turns to take.

**Comment by barryhunter** [comment] 2015-08-18 09:27
duplicate of #73

**Closed by barryhunter** 2015-08-18 09:27 UTC
