### ISSUE TITLE
Some Route numbers show up on bike maps in the US but are unreadable

### ISSUE THREAD

**Issue by A-Robustus** [barryhunter/classygmaps#82] opened 2015-09-05 00:19 UTC
I sent you a request recently about highway numbers not showing up. You mentioned that it seemed to be peculiar to the US. I just noticed that in the state of New York, the numbers are there, but they are not readable. I have attached a screen shot. Maybe this information will help you.
Thank You
![routenumbersusnewyork](https://cloud.githubusercontent.com/assets/13984249/9696648/2336f890-5342-11e5-963b-357888edf9ec.png)

**Comment by barryhunter** [comment] 2015-09-08 09:53
I'll close this seperate issue, and mark it as a duplicate of #80, that will automatically link the two. 

Havent looked any more into it, but maybe the scrrenshot will help thank you.,

**Closed by barryhunter** 2015-09-08 09:53 UTC
