### ISSUE TITLE
print map without wording on left side of page

### ISSUE THREAD

**Issue by cagnew** [barryhunter/classygmaps#22] opened 2015-06-03 05:51 UTC

**Comment by terrymap** [comment] 2015-06-06 04:22
yes yes yes please! classic google maps printing

**Comment by mohrjo** [comment] 2015-06-11 04:52
Yes please provide the feature of allowing the user to zoom in/out right/left to position the page that is to be printed so the user set the coverage.

**Comment by barryhunter** [comment] 2015-07-07 20:14
I'm marking this a duplicate of 
https://github.com/barryhunter/classygmaps/issues/29

its not exactly the same request, but will consider that one a general request for better printing options.

**Closed by barryhunter** 2015-07-07 20:14 UTC
