### ISSUE TITLE
Entering coordinates returns something other than the exact point

### ISSUE THREAD

**Issue by frankyfranky** [barryhunter/classygmaps#39] opened 2015-06-13 15:58 UTC
If you type in coordinates, it brings you to a location which is nearby, but not correct.  Maybe it is returning the nearest road/point of interest instead of the exact location?

For example let's try the Palace of Fine Arts.  The location is 37.802778,-122.448333.  Paste that into New Google Maps, or Bing Maps, and it places the marker right on the monument.  When you paste the coordinates into ClassyGMaps, it places the marker on the nearby road.

**Comment by barryhunter** [comment] 2015-06-14 15:43
I'll close this as a duplicate of https://github.com/barryhunter/classygmaps/issues/25 as its the same issue. That issue gives some background explanation.

**Closed by barryhunter** 2015-06-14 15:43 UTC
Labels: bug, duplicate
