### ISSUE TITLE
miles /kms

### ISSUE THREAD

**Issue by mrpaulhawkins** [barryhunter/classygmaps#74] opened 2015-08-15 07:54 UTC
Hello
great to see someone trying to revive the classics
good luck with your efforts
what about an option for miles /kms
apologies if this already exists.
just briefly had a look but option was not obvious to me.

**Comment by barryhunter** [comment] 2015-08-18 09:24
Duplicate of #72

**Closed by barryhunter** 2015-08-18 09:24 UTC
