### ISSUE TITLE
Printing with Street View imagery

### ISSUE THREAD

**Issue by AEGBRG** [barryhunter/classygmaps#45] opened 2015-06-28 19:19 UTC
Is there a way to incorporate this printing feature that was in Classic Google Maps? It was great to have street view for each step, as in this picture:

![printed-classic-maps](https://cloud.githubusercontent.com/assets/13089719/8397875/4a3b3258-1da0-11e5-96f4-ba8421aa7c26.png)

If you are able to add this feature that would be amazing. Either way though, thanks Barry for what you are doing!

**Comment by barryhunter** [comment] 2015-07-07 20:13
This is a duplicate of 
https://github.com/barryhunter/classygmaps/issues/29

**Closed by barryhunter** 2015-07-07 20:13 UTC
