### ISSUE TITLE
Options for Driving Directions

### ISSUE THREAD

**Issue by egoldobin** [barryhunter/classygmaps#69] opened 2015-07-28 11:58 UTC
How do I specify options for driving directions? Like "avoid tolls", etc...

**Comment by barryhunter** [comment] 2015-07-28 12:03
Not possible yet. Still a feature request.

**Comment by barryhunter** [comment] 2015-07-28 13:05
Duplicate of https://github.com/barryhunter/classygmaps/issues/19

**Closed by barryhunter** 2015-07-28 13:05 UTC
Labels: enhancement
