### ISSUE TITLE
Search Nearby!

### ISSUE THREAD

**Issue by Bdins1991** [barryhunter/classygmaps#46] opened 2015-06-29 14:03 UTC
Hello, I appreciate this so much! I am on a team of 12 and we use Google Maps extensively. I know someone else has already submitted this but I wanted to second the request for the classic google maps search nearby feature. It would make our lives if you could resurrect this feature on Classy Maps! Thank You!!

**Comment by barryhunter** [comment] 2015-07-07 19:58
duplicate of https://github.com/barryhunter/classygmaps/issues/44

**Closed by barryhunter** 2015-07-07 19:58 UTC
