### ISSUE TITLE
Option to get rid of Split-screen in Street-View

### ISSUE THREAD

**Issue by lol666** [barryhunter/classygmaps#27] opened 2015-06-04 00:18 UTC
This map needs the option to get rid of split screen in street-view. It's annoying and I want to view street-view in full screen.

**Comment by zinfl** [comment] 2015-06-07 05:18
Second that. Nice to have split screen sometimes, but would like to have an enlarged view more often.

**Comment by gnomontosunlight** [comment] 2015-06-07 18:03
Please, to me it would be nice just the other way around. So, nice to have an enlarged or full-screen view sometimes, and to have the spit screen always. For me, this split screen was the most important reason for wanting to have this ClassyGMap instead of the new Street View in the first place!

**Comment by barryhunter** [comment] 2015-06-08 10:05
Duplicate of https://github.com/barryhunter/classygmaps/issues/1

**Closed by barryhunter** 2015-06-08 10:05 UTC
